# fly.toml file generated for twilightsparkle on 2023-07-05T06:52:37-04:00

app = "twilightsparkle"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[mounts]
  source="fresh_data_machines"
  destination="/deno-dir/location_data"

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [services.concurrency]
    hard_limit = 5000
    soft_limit = 4500
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
