// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $api_comments_slug_ from "./routes/api/comments/[slug].ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $auth_callback from "./routes/auth/callback.ts";
import * as $auth_signin from "./routes/auth/signin.ts";
import * as $auth_signout from "./routes/auth/signout.ts";
import * as $auth_whoami from "./routes/auth/whoami.tsx";
import * as $blog_rss from "./routes/blog.rss.ts";
import * as $blog_slug_ from "./routes/blog/[slug].tsx";
import * as $blog_middleware from "./routes/blog/_middleware.ts";
import * as $blog_index from "./routes/blog/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $sitemap_xml from "./routes/sitemap.xml.ts";
import * as $xrpc_com_atproto_identity_resolveHandle from "./routes/xrpc/com.atproto.identity.resolveHandle.ts";
import * as $Button from "./islands/Button.tsx";
import * as $Comments from "./islands/Comments.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Input from "./islands/Input.tsx";
import * as $MastodonShare from "./islands/MastodonShare.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/api/comments/[slug].ts": $api_comments_slug_,
    "./routes/api/joke.ts": $api_joke,
    "./routes/auth/callback.ts": $auth_callback,
    "./routes/auth/signin.ts": $auth_signin,
    "./routes/auth/signout.ts": $auth_signout,
    "./routes/auth/whoami.tsx": $auth_whoami,
    "./routes/blog.rss.ts": $blog_rss,
    "./routes/blog/[slug].tsx": $blog_slug_,
    "./routes/blog/_middleware.ts": $blog_middleware,
    "./routes/blog/index.tsx": $blog_index,
    "./routes/index.tsx": $index,
    "./routes/sitemap.xml.ts": $sitemap_xml,
    "./routes/xrpc/com.atproto.identity.resolveHandle.ts":
      $xrpc_com_atproto_identity_resolveHandle,
  },
  islands: {
    "./islands/Button.tsx": $Button,
    "./islands/Comments.tsx": $Comments,
    "./islands/Counter.tsx": $Counter,
    "./islands/Input.tsx": $Input,
    "./islands/MastodonShare.tsx": $MastodonShare,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
