// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/gpt/decode.ts";
import * as $3 from "./routes/api/gpt/pairs.ts";
import * as $4 from "./routes/api/gpt/tokenize.ts";
import * as $5 from "./routes/api/joke.ts";
import * as $6 from "./routes/blog/[slug].tsx";
import * as $7 from "./routes/blog/_middleware.ts";
import * as $8 from "./routes/blog/index.tsx";
import * as $9 from "./routes/index.tsx";
import * as $10 from "./routes/sitemap.xml.ts";
import * as $11 from "./routes/xrpc/com.atproto.identity.resolveHandle.ts";
import * as $$0 from "./islands/Button.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/Input.tsx";
import * as $$3 from "./islands/MastodonShare.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/gpt/decode.ts": $2,
    "./routes/api/gpt/pairs.ts": $3,
    "./routes/api/gpt/tokenize.ts": $4,
    "./routes/api/joke.ts": $5,
    "./routes/blog/[slug].tsx": $6,
    "./routes/blog/_middleware.ts": $7,
    "./routes/blog/index.tsx": $8,
    "./routes/index.tsx": $9,
    "./routes/sitemap.xml.ts": $10,
    "./routes/xrpc/com.atproto.identity.resolveHandle.ts": $11,
  },
  islands: {
    "./islands/Button.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/Input.tsx": $$2,
    "./islands/MastodonShare.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
