// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_middleware.tsx";
import * as $4 from "./routes/api/joke.ts";
import * as $5 from "./routes/auth/callback.ts";
import * as $6 from "./routes/auth/signin.ts";
import * as $7 from "./routes/auth/signout.ts";
import * as $8 from "./routes/auth/whoami.tsx";
import * as $9 from "./routes/blog.rss.ts";
import * as $10 from "./routes/blog/[slug].tsx";
import * as $11 from "./routes/blog/_middleware.ts";
import * as $12 from "./routes/blog/index.tsx";
import * as $13 from "./routes/index.tsx";
import * as $14 from "./routes/sitemap.xml.ts";
import * as $15 from "./routes/xrpc/com.atproto.identity.resolveHandle.ts";
import * as $$0 from "./islands/Button.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/Input.tsx";
import * as $$3 from "./islands/MastodonShare.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/_middleware.tsx": $3,
    "./routes/api/joke.ts": $4,
    "./routes/auth/callback.ts": $5,
    "./routes/auth/signin.ts": $6,
    "./routes/auth/signout.ts": $7,
    "./routes/auth/whoami.tsx": $8,
    "./routes/blog.rss.ts": $9,
    "./routes/blog/[slug].tsx": $10,
    "./routes/blog/_middleware.ts": $11,
    "./routes/blog/index.tsx": $12,
    "./routes/index.tsx": $13,
    "./routes/sitemap.xml.ts": $14,
    "./routes/xrpc/com.atproto.identity.resolveHandle.ts": $15,
  },
  islands: {
    "./islands/Button.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/Input.tsx": $$2,
    "./islands/MastodonShare.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
